#!/bin/sh

# Copyright (C) 2025 RZ781
#
# This file is part of txtris.
#
# txtris is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# txtris is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <https://www.gnu.org/licenses/>.

if [ -z "$LIBCITRUS_PATH" ] ; then
	LIBCITRUS_PATH=libcitrus
	cd libcitrus || exit $?
	./build || exit $?
	cd .. || exit $?
fi

gcc -Wall -Wextra -Wpedantic -o txtris \
	-I"$LIBCITRUS_PATH"/include txtris.c -L"$LIBCITRUS_PATH"  -Wl,-Bstatic -lcitrus -Wl,-Bdynamic \
	$(pkg-config --cflags --libs ncursesw) || exit $?
